name: eguasti
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.2+4

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_map_marker_cluster:
    git:
      url: https://github.com/matteomrz/flutter_map_marker_cluster.git
      ref: f45d4aa97944fb8175894c747ee292a10fbd7369


  android_intent_plus: ^5.3.1
  chopper: ^8.3.0
  dartx: ^1.2.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  flutter_map: ^8.2.1
  flutter_svg: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  latlong2: ^0.9.1
  package_info_plus: ^8.3.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  workmanager: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.7.1
  chopper_generator: ^8.3.1
  flutter_lints: ^6.0.0
  json_serializable: ^6.11.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/marker_red.svg
    - assets/marker_yellow.svg
    - assets/github.svg
