# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy a new production version to the Google Play"
  lane :deploy do
    gradle(task: ":androidApp:clean :androidApp:bundleRelease")
    upload_to_play_store(
      aab: "androidApp/build/outputs/bundle/release/androidApp-release.aab",
      rollout: "0.2",
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
