name: Android CI Workflow

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    container: ghcr.io/cirruslabs/flutter:3.10.6
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - name: Build project
        run: flutter build apk
